- SlashGPT.py
> manifest_key

- lib/chat_session.py
Jupyter agent でエラーが起こっていたので修正しました。
> handle no action case gracefully

- SlashGPT.py
https://github.com/snakajima/SlashGPT/pull/66#discussion_r1302734551
> import readline

- lib/chat_session.py
- manifests/roles1/mag2.json
- manifests/roles2/olympic.json
> add db_type

- lib/chat_config.py
- lib/chat_config_base.py
- lib/chat_session.py
- samples/SimpleGPT.py
For SimpleGPT, I simplified ChatConfig so that it works without manifests.
> Chat config base

- notebooks/SlashGPT_on_GoogleColab.ipynb
add /notebooks/SlashGPT_on_GoogleColab.ipynb
> Add SlashGPT_on_GoogleColab.ipynb

- README.md
- notebooks/SlashGPT_on_GoogleColab.ipynb
- README.md
- Add link to Google Colab version 
- notebooks/SlashGPT_on_GoogleColab.ipynb
- fixed file path
- update comment
- update initial setting
> update SlashGPT on Google Colab and README.md

- notebooks/SlashGPT_on_GoogleColab.ipynb
- src/slashgpt/SlashGPT.py
> add KeyboardInterrupt handler

- src/slashgpt/SlashGPT.py
- src/slashgpt/function/function_call.py
function_callのinfo情報はverboseに変更
codeを整形して表示
> update print in function call

- src/slashgpt/SlashGPT.py
- src/slashgpt/history/base.py
- src/slashgpt/history/storage/file.py
- src/slashgpt/history/storage/memory.py
This allows:
/spacex
Who is the CEO of SpaceX
/cal -chain
Invite him to a meeting at 3pm tomorrow.
> Chained session

- manifests/manifests.json
- manifests/ss/blip2.json
- resources/functions/blip2.json
- resources/module/blip2.py
```
You(blip2): /sample
You(blip2): What is written on this image?  https://upload.wikimedia.org/wikipedia/commons/e/ed/TaroTokyo20110213-TokyoTower-01min.jpg
function(generated_text_from_image_url): {"result": "success", "text": "a large tower with a red and white tower"}
Agent(blip2): The image appears to show a large tower with a red and white color scheme.
You(blip2): 
```
> add blip2 agent

- .gitignore
- samples/config_sample.py
- server.py
- src/slashgpt/SlashGPT.py
- src/slashgpt/chat_context.py
- src/slashgpt/chat_session.py
- src/slashgpt/function/function_call.py
- src/slashgpt/history/base.py
- src/slashgpt/history/storage/abstract.py
- src/slashgpt/history/storage/file.py
- src/slashgpt/history/storage/log.py
- src/slashgpt/history/storage/memory.py
- src/slashgpt/history/storage/pseudo_sql.py
- tests/chat_history/test_history-file-storage.py
- tests/chat_history/test_history-talk.py
- tests/chat_history/test_history.py
Renamed base.py to chat_context and moved it under src/slashgpt
Changed its class name from ChatHistory to ChatContext
Added setMemory() and memory() methods to ChatContext
Added setMemory() and memory() methods to ChatHistoryAbstractStorage
Implemented them in ChatHistoryFileStorage and ChatHistoryMemoryStorage, but not in ChatHistoryPseudoSQLStorage
> Chat context

- src/slashgpt/llms/engine/openai_gpt.py
logprobs is only for text completion API, not chat API. I'm removing it for now.
> removed logprobs for now

- tests/llm_engine/test_engine.py
- tests/llm_engine/test_llm.py
1. MockLlmEngine(LLMEngineBase) calls super().__init__(llm_model).
2. Test function_call
> Test function call

- src/slashgpt/manifest.py
- tests/manifests/test_manifest.py
Manifest loads and validate functions when the instance was created, so that calling functions() is not expensive.
> Manifest: Preload functions

- manifests/main/knowledge.yml
- resources/functions/knowledge.json
- src/slashgpt/function/function_action.py
- src/slashgpt/function/function_call.py
- src/slashgpt/utils/utils.py
1. Created "knowledge" agent in main (/knowledge)
2. Knowledge agent generates a knowledge graph using function_call
3. Introduced CallType.DEBUG, which simply dumps the function arguments
4. Knowledge agent uses that mechanism to dumps the knowledge graph in JSON (for now)
> Knowledge graph generation

- src/slashgpt/chat_app.py
- src/slashgpt/chat_session.py
https://github.com/snakajima/SlashGPT/commit/30192d8a0d14829aa187a7f0d7f8b96c2840b712
After the change to remove memory from history, it seems that memory is no longer being merged.
I changed it so that memory is merged during switch_session.
before
after
> Add support for merging memory in switch_session method

- samples/websocket/agent.py
- samples/websocket/client.py
- samples/websocket/requirements.txt
- samples/websocket/server.py
This is a prototype of websocket-based AI chatbot.
1. server.py: A websocket server, which simply enables a group chat among all the clients.
2. client.py: A web socket client, which connects to the server and allows the user to send a message to the chat group.
3. agent.py: An AI agent, which responds to all the massage in the chat room using LLM.
1. Run pip install -r requirements.txt in samples/websocket folder. (only once)
2. Open three terminals (A, B, C)
3. Start server.py on terminal A
4. Start agent.py on terminal B
5. Start client.py on terminal C
6. Start typing questions on terminal C
> Websocket prototype

- manifests/kgraph/knowledge.yml
- src/slashgpt/chat_session.py
- src/slashgpt/function/function_action.py
- src/slashgpt/manifest.py
Fixed a bug dealing with a dictionary passed via memory. 
Fixed another bug dealing with non-alphabet character passed via memory.
> pass dictionary via memory

- manifests/main/codereview.yml
- samples/CodeReview.py
```
git show  -U9999  422b8ea64a21c528f79f82ff219fb83643c30569 | python -m samples.CodeReview
```
```
Agent(codereview): 更新されたコードは、ChatSessionを導入しているようです。ChatSessionは、ユーザーとの対話をシミュレートするためのクラスです。
改善点としては、以下の点が挙げられます：
1. `from dotenv import load_dotenv`が追加されていますが、このコードは実際に使用されていません。不要なので削除しましょう。
2. `current_dir = os.path.dirname(__file__)`のような変数は、コード内で使用されていません。不要なので削除しましょう。
3. `MyLlmEngine`クラスが正しく綴られていません。変数名を修正して`MyLlmEngine`に統一しましょう。
4. `engine.chat_completion`のテストで、`assert res == "hello"`となっていますが、実際のコードでは`res = "foo"`となっています。テストとコードの整合性を確認しましょう。
5. `test_bar`関数内で`ChatSession`クラスを使用していますが、この部分のテストコードが不完全です。`session.call_loop(process_event)`の後に`assert res == "hello"`と書かれていますが、このテストでは実際には`res`がどのように変化するかを検証していません。`ChatSession`の使い方に合わせてテストを修正しましょう。
以上が今回の更新内容に対する指摘と改善点です。
```
> add code review agent

- src/slashgpt/slashbot.py
```
slashbot codereview -l  
```
```
Manifest list
noteable: WIP: Noteable - Create notebooks in Python, SQL, and Markdown to explore data, visualize, and share notebooks with everyone.
webpilot: Web Pilot AI - Allows users to input a URL, retrieves the web page content, and returns a comprehensible summary of it.
code_llama: Code Interpreter with Llamma2 - 
codereview: Code review - 
news2: News News - 
dispatcher: Main Dispatcher - 
```
> add options

- manifests/main/commit.yml
Generate commit comments from git diff.
```
Add hono
- Add a rewrite rule in firebase.json to route requests to the "/api/*" path to the "hono_server" function in the "asia-northeast1" region.
- Add the "hono" package as a dependency in the package.json file.
- Add a new file "hono.ts" in the "functions/src/functions/server" directory, which contains the implementation for the "hono_server" function.
- Update the "index.ts" file to export the "hono_server" function.
- Add a new file "hono.ts" in the "functions/src/wrappers/server" directory, which wraps the "hono_server" function with Firebase Functions configuration.
```
> commit comment manifest

- src/slashgpt/slashbot.py
fix  error when both list and agentname option exist
> update --list option

- server.py
Server also supports changing history from context
> fix: server function call

- tests/llm_engine/test_llm.py
> added missing _token_usage

- Dockerfile
- Makefile
- README.md
See issue #285 this PR enables...
Dockerfile now conditionally builds with minimal requirements or full requirements if docker build --build-arg BUILD=full set.
Makefile now has `make docker` which will build a full requirements and let you edit your development source
README is markdownlint'ed
> fix: Docker full or minimal, make docker, README clean
